### ISSUE TITLE
subscriber getting unexpected item.

### ISSUE THREAD

**Issue by mooncell07** [mooncell07/Azaka#1]
https://github.com/mooncell07/Azaka/blob/c3dd7e9bc6086cd4928f43827762422cc6983e8b/azaka/websocket/protocol.py#L37-L41

Here for some reason the `self.subscriber` is getting `ok` even though there's an if condition specifically for that.

**Comment by zeffo** [comment]
ok♦

**Comment by mooncell07** [comment]
> ok♦

AAAAAAA THANKS!!! AM RETARDED
